apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: enterprise-system-20260623-135112-5obgo03f8j9f-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: enterprise-system-20260623-135112-5obgo03f8j9f.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: enterprise-system-20260623-135112-5obgo03f8j9f-service
            port:
              number: 80
