apiVersion: v1
kind: Service
metadata:
  name: enterprise-system-20260623-135112-5obgo03f8j9f-service
spec:
  selector:
    app: enterprise-system-20260623-135112-5obgo03f8j9f
  ports:
  - port: 80
    targetPort: 8000
  type: ClusterIP
